### PR TITLE
CMake build for Memtailor

### PR DESCRIPTION
**Pull request by mahrud**
This PR improves the CMakeLists.txt file in the master branch to be a full replacement for the configure.ac script. This is how you would "configure", build, test, and install using CMake:
```
cmake -GNinja -B tmp -S . -DCMAKE_INSTALL_PREFIX=/usr
cmake --build tmp
cmake --build tmp --target test
cmake --install tmp
```
The `-GNinja` option instructs CMake to produce `build.ninja` files instead of `Makefiles` to go with the Ninja build system, which is faster and more efficient than `make`.

### CODE REVIEW

**Comment by mahrud** [comment]
PS: the PR also fixes incorrect permissions on source files.

**Comment by mikestillman** [comment]
@DanGrayson The cmake version here runs fine, on my mac.  I think I'll accept this pull request.  How should I/we change the commit numbers in M2 to use this?

**Comment by DanGrayson** [comment]
Mahrud can add the change in commit numbers to his current cmake pull request, so you don't have to.

**Comment by mahrud** [comment]
I already have, see: https://github.com/Macaulay2/M2/pull/1190#issuecomment-634191896

**Comment by mahrud** [comment]
Oh, but I haven't changed it to track the Macaulay2 fork yet. I will do that once the other two are also merged so builds in the meantime don't fail.

**Pull request merged**
